name: RuboCop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true # bundle installのキャッシュが有効化
    - name: Run RuboCop
      run: bundle exec rubocop --parallel --auto-correct-all
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Apply RuboCop auto-correct"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions <actions@github.com>"
        file_pattern: "**/*.rb"
    - name: Check for changes
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "Changes were made by RuboCop"
          exit 1
        else
          echo "No changes were made by RuboCop"
        fi